name: Publish Sites

on:
  push:
    branches:
      - master

jobs:
  publish-cyber:
    uses: cyberia-to/.github/.github/workflows/publish-to-netlify.yml@main
    with:
      environment: "cyber"
      site-name: "cyber docs"
      home: "cyber"
      title: "Cyber"
      favorites: "cyberia,cyber valley,bostrom,cyber,aicosystem,ask,learn,collective intelligence,superintelligence,concepts,🫦 space pussy,knowledge theory,space pussy,neuron,particle,tokens,cyberlink,cybergraph,truth machine,cybernet,soft3,projects,todo,aips,cyb,about this metagraph"
    secrets: inherit

  publish-cvland:
    uses: cyberia-to/.github/.github/workflows/publish-to-netlify.yml@main
    with:
      environment: "cvland"
      site-name: "cvland docs"
      home: "cyberia"
      title: "Cyberia"
      favorites: "cv.land,projects,github"
    secrets: inherit
