name: Publish Sites

on:
  push:
    branches:
      - master

jobs:
  publish-cyber:
    environment: cyber
    uses: cyberia-to/.github/.github/workflows/publish-to-netlify.yml@main
    with:
      site-name: "cyber docs"
      home: "cyber"
      title: "Cyber"
      favorites: "cyberia,cyber valley,bostrom,cyber,aicosystem,ask,learn,collective intelligence,superintelligence,concepts,🫦 space pussy,knowledge theory,space pussy,neuron,particle,tokens,cyberlink,cybergraph,truth machine,cybernet,soft3,projects,todo,aips,cyb,about this metagraph"
    secrets:
      PINATA_JWT: ${{ secrets.PINATA_JWT }}
      PINATA_GATEWAY: ${{ secrets.PINATA_GATEWAY }}
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      PLAUSIBLE_SCRIPT_ID: ${{ secrets.PLAUSIBLE_SCRIPT_ID }}

  publish-cvland:
    environment: cvland
    uses: cyberia-to/.github/.github/workflows/publish-to-netlify.yml@main
    with:
      site-name: "cvland docs"
      home: "cyberia"
      title: "Cyberia"
      favorites: "cv.land,github projects,github structure"
    secrets:
      PINATA_JWT: ${{ secrets.PINATA_JWT }}
      PINATA_GATEWAY: ${{ secrets.PINATA_GATEWAY }}
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      PLAUSIBLE_SCRIPT_ID: ${{ secrets.PLAUSIBLE_SCRIPT_ID }}
